api_platform:
    title: 'Di Wino REST API'
    description: 'API to manage a search of wine.'
    version: '1.0.5'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
          apiKey:
            name: Authorization
            type: header
