#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login:
    path:       /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST

register:
    path:       /register
    controller: App\Controller\RegistrationController::register
    methods: GET|POST

app_logout:
    path: /logout
    methods: GET

wine_red:
    path: /wine_red
    methods: GET|POST

wine_red:
    path: /wine_rose
    methods: GET|POST

wine_red:
    path: /wine_white
    methods: GET|POST
# A venir si ont crée un éspace utilisateurs
# users:
#     path: /profile
#     methods: GET