# index:
#     path: /
#     controller: App\Controller\HomePageController::index
login:
    path:       /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST
api_login_check:
    path: /api/login_check

register:
    path:       /register
    controller: App\Controller\RegistrationController::register
    methods: GET|POST

app_logout:
    path: /logout
    methods: GET

wine_red:
    path: /wine_red
    controller: App\Controller\HomePageController::wine_red
    methods: GET|POST

wine_rose:
    path: /wine_rose
    controller: App\Controller\HomePageController::wine_rose
    methods: GET|POST

wine_white:
    path: /wine_white
    controller: App\Controller\HomePageController::wine_white
    methods: GET|POST
# A venir si ont crée un éspace utilisateurs
# users:
#     path: /profile
#     methods: GET